# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building..."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 15 seconds."
    - sleep 15
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - apt update
    - apt install python3 -y
    - apt install python3-pip -y
    - apt install python3-venv -y
    - python3 -m venv build_environment
    - source build_environment/bin/activate
    - pip install pylint
    - pylint src/*/*.py

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
